/**
 * Menu snapshot domain model.
 *
 * Immutable snapshots of raw provider menu data (ADR 0006: Menu Ownership).
 * These are append-only records that preserve the exact menu state as reported
 * by the provider at a specific point in time, enabling diagnosis and audit.
 * The raw menu is stored as a complete ProviderMenu JSON structure.
 */

import type { ProviderMenu } from '@/modules/spoton/domain/menu';

/**
 * Immutable snapshot of a provider menu at a specific point in time.
 * Maps to the `spoton_menu_snapshots` table.
 */
export interface MenuSnapshot {
  /** Unique identifier for this snapshot. */
  readonly id: string;
  /** Restaurant this menu belongs to. */
  readonly restaurantId: string;
  /** Location this menu is for. */
  readonly locationId: string;
  /** Opaque provider version string for change detection. */
  readonly menuVersion: string;
  /** Complete raw provider menu data. */
  readonly rawMenu: ProviderMenu;
  /** When the provider reported this snapshot (from ProviderMenu.retrievedAt). */
  readonly retrievedAt: Date;
  /** When this snapshot was stored in our system. */
  readonly createdAt: Date;
}

/**
 * Input for creating a new menu snapshot.
 * The id and createdAt will be generated by the repository.
 */
export interface CreateMenuSnapshotInput {
  readonly restaurantId: string;
  readonly locationId: string;
  readonly menuVersion: string;
  readonly rawMenu: ProviderMenu;
  readonly retrievedAt: Date;
}

// Made with Bob
