/**
 * Menu mapping domain model.
 *
 * Stable AETHER ↔ SpotOn ID mappings that survive provider changes (ADR 0006).
 * These mappings decouple our permanent identifiers from provider IDs, allowing
 * us to track entities across provider changes and detect when mappings break.
 * Broken mappings are flagged explicitly, never auto-remapped.
 */

/**
 * Lifecycle status of a menu mapping.
 * - active: Current, valid mapping
 * - broken: Provider ID no longer exists in snapshots
 * - archived: Intentionally retired by staff
 */
export type MappingStatus = 'active' | 'broken' | 'archived';

/**
 * Type of menu entity being mapped.
 */
export type EntityType = 'category' | 'item' | 'modifier';

/**
 * Stable mapping between AETHER and provider identifiers.
 * Maps to the `menu_mappings` table.
 */
export interface MenuMapping {
  /** Unique identifier for this mapping record. */
  readonly id: string;
  /** Restaurant this mapping belongs to. */
  readonly restaurantId: string;
  /** Location this mapping is for. */
  readonly locationId: string;
  /** Type of entity being mapped. */
  readonly entityType: EntityType;
  /** Our permanent, stable identifier for this entity. */
  readonly aetherId: string;
  /** Provider's identifier (categoryId, itemId, or modifierId). */
  readonly providerId: string;
  /** Provider-reported name for display and debugging. */
  readonly providerName: string;
  /** Current lifecycle status of this mapping. */
  readonly mappingStatus: MappingStatus;
  /** Most recent snapshot where this provider ID was observed. */
  readonly lastSeenSnapshotId: string | null;
  /** When this mapping was created. */
  readonly createdAt: Date;
  /** When this mapping was last updated. */
  readonly updatedAt: Date;
  /** When this mapping was detected as broken (null for active/archived). */
  readonly brokenAt: Date | null;
}

/**
 * Input for creating a new menu mapping.
 * The id, createdAt, and updatedAt will be generated by the repository.
 */
export interface CreateMenuMappingInput {
  readonly restaurantId: string;
  readonly locationId: string;
  readonly entityType: EntityType;
  readonly aetherId: string;
  readonly providerId: string;
  readonly providerName: string;
  readonly lastSeenSnapshotId?: string | null;
}

/**
 * Input for updating an existing menu mapping.
 */
export interface UpdateMenuMappingInput {
  readonly providerName?: string;
  readonly mappingStatus?: MappingStatus;
  readonly lastSeenSnapshotId?: string | null;
  readonly brokenAt?: Date | null;
}

/**
 * Check if a mapping is currently active.
 */
export function isActive(mapping: Pick<MenuMapping, 'mappingStatus'>): boolean {
  return mapping.mappingStatus === 'active';
}

/**
 * Check if a mapping is broken (provider ID no longer exists).
 */
export function isBroken(mapping: Pick<MenuMapping, 'mappingStatus'>): boolean {
  return mapping.mappingStatus === 'broken';
}

/**
 * Create an update input to mark a mapping as broken.
 */
export function markBroken(): UpdateMenuMappingInput {
  return {
    mappingStatus: 'broken',
    brokenAt: new Date(),
  };
}

/**
 * Create an update input to mark a mapping as archived.
 */
export function markArchived(): UpdateMenuMappingInput {
  return {
    mappingStatus: 'archived',
    brokenAt: null,
  };
}

// Made with Bob
